pipeline {
    agent {
        node {
           label 'AGENT-1'
        }
    }
    // parameters {
    //     string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')

    //     text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')

    //     // booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')
    //     booleanParam(name: 'DEPLOY', defaultValue: false, description: 'Toggle this value')

    //     choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')

    //     password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    // }
    environment{
        COURSE = "jenkins"
    }
    options {
        timeout(time: 60, unit: 'MINUTES')
        disableConcurrentBuilds() 
        ansiColor('xterm')

    }
    stages {
        stage('init') {
            steps {
                script{
                    withAWS(region:'us-east-1',credentials:'aws-creds') {
                        sh """
                            cd 00-vpc
                            terraform init
                        """
                    }
                }
            }
        }
        // poll scm
        stage('plan') {
            steps {
                script{
                    withAWS(region:'us-east-1',credentials:'aws-creds') {
                        sh """
                           cd 00-vpc
                           terraform plan
                        """
                    }
                }
            }
        }
        stage('Deploy') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
                submitter "alice,bob"
                parameters {
                    string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                }
            }
            // when {
            //     expression { "$params.DEPLOY" == "true" }
            // }
            steps {
                script{
                    withAWS(region:'us-east-1',credentials:'aws-creds') {
                        sh """
                            cd 00-vpc
                            terraform apply -auto-approve
                        """
                    }
                }
            }
        }
        stage('Trigger SG') {
            steps {
                script {
                    build job: '10-sg',
                        wait: false, // Wait for completion
                        propagate: false // Propagate status
                }
            }
        }
    }
    post { 
        always { 
            echo 'I will always say Hello again!'
            cleanWs()
        }
        success {
           echo 'I will run if success'
        }
        failure {
            echo 'I will run if failure'
        }
        aborted {
            echo ' pipe line aborted'
        }
    }
}